name: big-data
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - blast>=2.7.1
  - cd-hit>=4.8.1
  - ipycytoscape
  - matplotlib
  - clustalo
  - numpy>=1.18.5
  - python=3.8
  - python-dateutil>=2.8.1
  - pytz
